### ISSUE TITLE
Option to restore vanilla sun.

### ISSUE THREAD

**Issue by xpdlx** [WoMspace/Epoch-Shader#10]
Hey, I love this shaderpack. It's super unique!

It'd be cool if there was an option to make it so the sun and moon don't rotate like in the screenshot below.

![screenshot](https://github.com/WoMspace/Epoch-Shader/assets/39009376/66aae3e9-7690-46fe-93b8-6add16dddaa8)

I assume this was done to change the path of the sun and moon to make the shadows come from an angle? I personally don't really like the look of it and I can't seem to find a way to change it. I'm using Iris shaders on 1.20.2.

A way to modify the rotation would be really cool.
Maybe a way to modify the sun's trajectory could be cool too?

I noticed that in the last picture in the README.md, the sun is just a white circle (which I do quite like). I haven't been able to get the sun to look like that (maybe because I'm using iris? I have had the same issue mentioned in #6 as well).

**Comment by WoMspace** [comment]
Added a Sun Angle slider at [World] -> [Lighting] -> Sun Angle. Will be in next release.
