### ISSUE TITLE
Shadows don't work with oculus/rubidium

### ISSUE THREAD

**Issue by Ertoranzo** [WoMspace/Epoch-Shader#12]
![2024-07-17_14 00 48](https://github.com/user-attachments/assets/bf928b6d-1682-4a63-83fa-dcc1b036dbb6)
![2024-07-17_14 04 39](https://github.com/user-attachments/assets/8d44d1cc-6c05-4f04-8628-a8e24de19a94)

**Comment by Ertoranzo** [comment]
I tested both with the same settings and turing on/off the shadow option on oculus doesn't change anything. It always looks like this.
![2024-07-17_18 24 33](https://github.com/user-attachments/assets/e4b819a9-9a49-4883-8201-a61198fa9ba4)

**Comment by WoMspace** [comment]
Unfortunately I do not provide any support to oculus/rubidium as they are unofficial ports of iris and sodium. There are alphas of official neoforge ports for iris and sodium, please try those or use optifine.
