### ISSUE TITLE
Blocks look really weird and I can see through them a bit

### ISSUE THREAD

**Issue by Jaxjdude12342** [WoMspace/Epoch-Shader#13]
I can see through the blocks a bit and the block are very jankily viewed when i use the shader

**Comment by Jaxjdude12342** [comment]
![2024-07-28_17 55 24](https://github.com/user-attachments/assets/3369b14a-04ae-47e5-aefd-532aff1d307f)
It looks like this

**Comment by Jaxjdude12342** [comment]
Never mind, the textures of other items are just kind of weirdly put in in like lines into item icons along with the original item as well. the only thing that isn't affected are chests, beds, banners, mob heads, the conduit, weathered copper + waxed weathered copper, stripped jungle log and wood, red concrete, and probably other stuff that I haven't discovered yet. By the way the shaders also mess with mod textures too.

**Comment by WoMspace** [comment]
This is a known driver issue. The fix is to restart your game client every time you change shader.

**Comment by Jaxjdude12342** [comment]
Thank you! That should help



-Jax
