### ISSUE TITLE
blue lines in BnW profile (Iris)

### ISSUE THREAD

**Issue by mirususamongus** [WoMspace/Epoch-Shader#6]
Shader ver: Epoch shader ver v1.3.1
Shader loader:  iris mc1.19.4-1.6.3
Issue: when choosing the default black and white profile, bright blue lines appear instead of black cinematic lines

![2023-06-05_03 01 45](https://github.com/WoMspace/Epoch-Shader/assets/80936529/09b61a27-923f-47af-9316-c2d4d6bd4485)
![2023-06-05_03 01 28](https://github.com/WoMspace/Epoch-Shader/assets/80936529/f767cf1b-7b9b-46f4-a003-33fec4e3ae59)

**Comment by WoMspace** [comment]
I fixed this at some point in the last few months 😅 will be in the next release
