### ISSUE TITLE
visible outline on hand and tools in bokeh mode

### ISSUE THREAD

**Issue by mirususamongus** [WoMspace/Epoch-Shader#7]
Shader ver: Epoch shader ver v1.3.1
Shader loader:  iris mc1.19.4-1.6.3
Issue: The ability to create a bokeh effect is what I like most about this shader, but for some reason, the more this effect, the more visible the contour on the hand and other tools (if i increase lens focal).
![2023-06-05_03 06 42](https://github.com/WoMspace/Epoch-Shader/assets/80936529/59515495-65d3-4a7b-80e8-4dee79923b97)
![Inked2023-06-05_03 06 23](https://github.com/WoMspace/Epoch-Shader/assets/80936529/d104de2d-9062-4985-95be-a7fc36463928)

**Comment by WoMspace** [comment]
Added an option to turn off Circle of Confusion LOD
[Debug] -> DOF_COC_LOD
Note that this is enabled by default to fix some other issues with Depth of Field. Turning it off will fix the hand issue but some other artefacts may appear.
