### ISSUE TITLE
small bug with light in the nether

### ISSUE THREAD

**Issue by mirususamongus** [WoMspace/Epoch-Shader#8]
Shader ver: Epoch shader ver v1.3.1
Shader loader: iris mc1.19.4-1.6.3
Issue: I noticed that for almost every profile, when in the nether, the shadows break a little. the problem is that they are almost black, and when breaking blocks in places where there is a shadow, the particles of destruction are very bright. I also noticed that the shadow falls strangely on the sides of some blocks.
![2023-06-05_03 19 22](https://github.com/WoMspace/Epoch-Shader/assets/80936529/bff47fe2-5bd8-42c3-a420-11755dc839f6)
![2023-06-05_03 19 55](https://github.com/WoMspace/Epoch-Shader/assets/80936529/6e3baf54-4ec0-4919-bcc9-7a2842f1419f)
![2023-06-05_03 19 59](https://github.com/WoMspace/Epoch-Shader/assets/80936529/93f013a7-cf17-4006-ae10-3bbcca54b809)
![2023-06-05_03 20 05](https://github.com/WoMspace/Epoch-Shader/assets/80936529/214dce96-4660-45cf-9224-d423702159ed)

**Comment by WoMspace** [comment]
Regarding the dark shadows, you can increase the Minimum Light setting in [World] -> [Lighting] -> Minimum Light to make the shadows not be completely black.
I have also just added a workaround that darkens particles in the nether.
